namespace: circuit-breaker-app
replicaCount: 3

image:
  repository: d4rkghost47/python-circuit-svc-3
  pullPolicy: IfNotPresent
  tag: 

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

podDisruptionBudget:
  enabled: true
  minAvailable: 2

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health
    port: http

readinessProbe:
  httpGet:
    path: /health
    port: http

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

