apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-svc-3
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: git@github.com:evil-cloud/resillience-poc-service-c-k8s.git
    targetRevision: HEAD
    path: .
    helm:
      valueFiles:
        - values.yaml
      skipSchemaValidation: false
      skipCrds: false

  destination:
    server: https://kubernetes.default.svc
    namespace: circuit-breaker-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - ignoreMissingValueFiles=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 5
