apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-svc-3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:evil-cloud/resillience-poc-service-c-k8s.git
    targetRevision: HEAD
    path: .
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: circuit-breaker-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
