apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "rollout-k8s.fullname" . }}-pdb
  labels:
    {{- include "rollout-k8s.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "rollout-k8s.selectorLabels" . | nindent 6 }}

