apiVersion: v1
kind: Service
metadata:
  name: {{ include "rollout-k8s.fullname" . }}
  labels:
    {{- include "rollout-k8s.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ include "rollout-k8s.fullname" . }}

